input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [traceId] {
    mutate {
      add_field => { "trace_id" => "%{traceId}" }
    }
  }
  
  if [level] {
    mutate {
      add_field => { "log_level" => "%{level}" }
    }
  }
  
  mutate {
    remove_field => ["@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-boot-logs-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}